cat > docker-compose.yml <<'YAML'
services:

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.5
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 10

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.9.0
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

  producer1:
    build: ./producers/producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - ENDPOINT_NAME=endpoint-1
    depends_on:
      - kafka

  producer2:
    build: ./producers/producer
    environment:
      - KAFKA_BROKER=kafka:9092
      - ENDPOINT_NAME=endpoint-2
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    environment:
      - KAFKA_BROKER=kafka:9092
      - OPENSEARCH_HOST=http://opensearch:9200
      - OPENSEARCH_INDEX=system-logs
    depends_on:
      - kafka
      - opensearch

  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=http://opensearch:9200
    depends_on:
      - opensearch

volumes:
  opensearch-data:
YAML
